plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
}

android {
    namespace "com.nice.library_splash"
    sourceSets {
        main {
            java.srcDirs = ['src/main/java']
        }
    }
}

dependencies {
    implementation libs.androidx.core.ktx
    implementation libs.androidx.fragment.ktx
    implementation rootProject.ext.thirdPartyAars.drouterApi
}
