apply plugin: 'activityGuard'

actGuard {
    enable = true
    whiteClassList = [
        "com.activityGuard.model.Bean",
        "org.bouncycastle.*",
        "app.lawnchair.*",
        "com.android.launcher3.*",
        "com.android.quickstep.*",
        "com.simplepdf.pdfeditor.*",
        "com.didi.drouter.*",
    ] as Set
    otherClassList = [
        "com.nice.screebkub.*"
    ] as Set
    changePackageList = [
        "com.nice.screebkub.*"
    ] as Set
    classNameCharPool = "abcdefghijklmnopqrstuvwxyz0123456789"
    dirNameCharPool = "abcdefghijklmnopqrstuvwxyz"
}

tasks.matching { it.name.startsWith("activityGuard") }.configureEach {
    notCompatibleWithConfigurationCache("ActivityGuard tasks access Task.project at execution time.")
}